#line 2 "t3-lex.c"

#line 4 "t3-lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char yytext[];

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[641] =
    {   0,
        0,    0,    0,    0,    0,    0,   96,   96,  119,  117,
      117,  117,  117,  112,  111,  109,  112,  113,  118,  118,
      110,  118,  116,  114,  118,  113,  118,  116,  114,   97,
       96,  118,    0,  103,  104,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  112,  109,  112,    0,  108,
      108,  106,    0,  115,  110,  115,   96,    0,    0,    0,
        0,    0,    0,  103,  103,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      108,  107,  115,    0,    0,    0,    0,  103,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    7,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    5,    0,    3,   24,
        0,  107,    0,    0,    0,  103,    0,    0,    0,    0,
        0,   10,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       67,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   66,    0,    0,    0,    0,    0,    0,
        3,  108,    0,    0,    0,    0,    0,    0,    0,   10,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   49,    0,    0,    0,    1,    0,    0,   13,    0,
       90,    0,    0,    0,   88,    0,    0,   11,    0,   76,
        0,   82,    0,    0,    0,    0,    0,   33,    0,    0,
        0,    0,    0,    0,    0,   47,    0,    0,   63,    0,

        0,   57,    0,    0,    0,    0,    0,    0,    0,    3,
        0,   94,    0,    0,   99,    0,    0,    0,   10,    0,
        0,   64,    0,    0,   78,    0,    0,    0,    8,   74,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    1,    0,    0,    0,    0,    0,    0,    0,   20,
       12,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   70,
        0,    0,    0,   92,    0,  101,    0,    0,   99,    0,
        0,    0,    0,    0,   64,    0,  102,   84,    0,    0,
       86,    0,    0,    0,    0,   80,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    1,    6,    0,
        0,    0,    0,   16,    0,    0,    0,    0,    0,    0,
       30,    0,    0,    0,    0,   37,    0,    0,    0,    0,
        0,    0,    0,   18,    0,   22,    0,    0,    0,   68,
        0,   93,    0,    0,    0,   99,    0,    0,    0,    0,
        0,   64,  102,    0,    0,    0,    8,    0,    4,    0,
        2,    0,    0,    0,    0,    0,    0,   53,    0,   48,
        0,    0,    0,   14,   91,   15,    0,   89,   77,   83,
       26,   28,    0,    0,    0,   34,   35,    0,    0,   39,
        0,    0,    0,   46,    0,    0,    0,    0,    0,   58,

        0,    0,    0,    0,   98,   95,    0,  100,    0,    0,
        0,   25,    0,  102,    0,   79,    0,   75,    2,    0,
        0,    9,    0,   53,    0,    0,    0,    0,   55,    0,
       72,    0,    0,    0,    0,    0,    0,    0,    0,   41,
        0,   44,    0,    0,   27,    0,    0,    0,   71,    0,
       65,   98,  100,    0,   54,    0,   25,    0,   85,   87,
        2,   81,    0,    0,   55,    0,    0,    0,    0,    0,
       17,    0,   31,    0,    0,   38,    0,    0,    0,    0,
       61,    0,   19,   23,   69,   98,  100,   54,    0,   56,
       25,    0,    0,   62,    9,    0,   50,   52,    0,   21,

        0,   29,   32,   36,   40,    0,    0,   45,    0,   54,
       56,    0,   62,   50,    0,    0,    0,   73,   42,   43,
        0,   56,    0,   62,    0,    0,    0,    0,    0,    0,
       51,    0,    0,   51,   59,    0,   60,   60,   60,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    6,    7,    6,    8,    6,    6,    6,    9,
       10,    6,    6,    6,   11,    6,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    6,    6,    6,
        6,    6,    6,    6,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       14,   15,   16,    6,   13,    6,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   13,   33,   34,   35,   36,   37,   38,   39,
       40,   13,   41,    6,   42,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[43] =
    {   0,
        1,    2,    2,    2,    2,    3,    4,    4,    3,    3,
        3,    4,    3,    5,    2,    4,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        4,    4
    } ;

static const flex_int16_t yy_base[657] =
    {   0,
        0,   15,   30,   72,  113,  154,    7,   22, 1054, 1055,
     1043,  191,  222,    0, 1055, 1049,  261, 1041,  298,   12,
     1036, 1055, 1039, 1038, 1037, 1055, 1030, 1055, 1055, 1055,
       36,   31, 1035, 1034,  335,  377,  401,   15,   24,   24,
     1018,   26,   28,   39,   36, 1011,   64, 1024, 1007, 1018,
       64, 1008, 1020,   44, 1003,    0, 1032,  439, 1024,    0,
     1023,  476,  518,   59, 1018,   90,  100,  997, 1013, 1008,
       98,  986,  560,  602, 1017, 1009,   86,  994, 1002, 1006,
      989,  997,  988,  986,  988,  996,  985,   61,  996,  980,
      994,  980,  983,  977,  974,  977,   67,   90,  982,   90,

       89,  985,  109,  110,  976,  973,  980,  985,  966,  972,
      966,  973,  963,  963,  970,  130,  991,  124,  951,  644,
      686,  982,  132,  953,  956,  967,  723, 1055,  954,  965,
      967,  952,  127,  955,  952,  957,  960,  963,  962,  961,
      958,  947,  125,  940,  953,  942,  939,  950,  119,  967,
      951,  965,  946,  933,  934,  934,  931,  928,  118,  926,
      930,  929,  113,  130,  925,  936,  937,  130,  925,  951,
      928,  927,  916,  929,  924,  920,  944,  930, 1055,  942,
      760, 1055,  919,  922,  925,  797,  920,  923,  904,  917,
      921, 1055,  915,  916,  906,  903,  892,  872,  875,  847,

      852,  855,  846,  160,  161,  850,  164,  171,  852,  851,
      864,  173,  843,  150,  176,  178,  844,  839,  842,  841,
      180,  838,  837,  157,  838,  825,  854,  821,  821,  851,
      814,  816,  201,  848,  814,  818,  828,  802,  819,  814,
      189,  834,  799,  830,  796,  193,  795,  819,  812,  210,
      794,  194,  806,  806,  205,  785,  205,  208,  794,  788,
      792,  215,  243,  796,  804, 1055,  797,  793,  814,  781,
      812,  779,  793,  776,  807,  765,  796,  795,  794,  793,
      760,  791,  758,  762,  768,  751,  756,  785,  752,  751,
      764,  767,  766,  749,  762,  777,  768,  746,  774,  743,

      756,  770,  728,  217,  739,  737,  757,  741,  755,  219,
      738,  753,  727,  738, 1055,  725,  208,  733,  222,  719,
      734, 1055,  219,  246,  746,  713,  261,  731, 1055,  743,
      710,  709,  263,  707,  245,  717,  254,  708,  709,  713,
      715,  279,  733,  697,  695,  694,  700,  277,  692,  719,
      718,  689,  688,  698,  687,  283,  681,  684,  690,  284,
      678,  693,  677,  686,  674,  691,  286,  287,  676,  703,
      670,  288,  701,  700,  674,  697,  675,  663,  308,  662,
      664,  669,  669,  675,  312,  669, 1055,  681,  648,  651,
      678,  645,  315,  648,  318,  675,  642,  655,  647,  641,

      638,  644,  638,  645,  666,  633,  634,  319,  663,  642,
      661,  660,  659,  658,  625,  655,  654,  653,  652,  289,
      650,  617,  640,  647,  290,  640,  607,  322,  620,  619,
      324,  608,  619,  634,  601,  632,  599,  630,  601,  628,
      595,  626,  607,  251,  611,  333,  316,  593,  590,  336,
      605,  350,  353,  592,  619,  590,  356,  617,  616,  602,
     1055,  585,  350,  580,  611,  589,  576, 1055,  580,   79,
      585,  587,  360,  598,  597,  596,  567,  594,  593,  592,
      591,  590,  557,  560,  555,  586,  585,  552,  555,  582,
      549,  361,  362,  580,  547,  578,  559,  548,  547,  574,

      573,  543,  570,  556, 1055, 1055,  555, 1055,  358,  545,
      552, 1055,  546,  364,  563,  556,  555,  554,  380,  553,
      539, 1055,  533,  550,  549,  530,  515,  524, 1055,  525,
      544,  511,  542,  513,  540,  511,  510,  537,  508,  535,
      502,  533,  500,  503,  529,  383,  528,  527,  526,  524,
      523,  385,  392,  509, 1055,  386,  396,  392,  521,  513,
      402,  512,  406,  481,  510,  479,  508,  482,  506,  477,
      504,  503,  502,  501,  500,  499,  498,  469,  468,  495,
      494,  475,  492,  491,  490,  409,  412,  424,  475, 1055,
      431,  469,  473, 1055,  438,  419,  468,  475,  442,  473,

      472,  471,  447,  442,  435,  434,  429,  422,  387,  449,
      453,  381,  456,  390,  356,  340,  329,  346,  328,  326,
      309,  459,  279,  462,  220,  207,  203,  201,  162,  185,
     1055,  146,  432,  107,   58,    8, 1055,  465,  468, 1055,
      876,  881,  886,  891,  894,  896,  900,  903,  905,  907,
      911,  915,  919,  923,  925,  927
    } ;

static const flex_int16_t yy_def[657] =
    {   0,
      641,  641,  642,  642,  643,  643,  644,  644,  640,  640,
      645,  646,  640,  647,  640,  640,  648,  649,  650,  649,
      640,  640,  649,  649,  649,  640,  640,  640,  640,  640,
      640,  640,  645,  645,  646,  651,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  647,  640,  648,  649,   58,
      649,  650,  652,  649,  640,  640,  640,  640,  640,  640,
      645,  653,  651,  651,  645,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  649,  654,  652,
      652,  649,  640,  640,  640,  640,  655,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      656,  640,  640,  640,  640,  655,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  656,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,

      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,    0,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640
    } ;

static const flex_int16_t yy_nxt[1098] =
    {   0,
       10,   10,   10,   10,   10,  640,  640,   12,  640,   31,
       31,   31,  640,   13,   10,   10,   10,   10,   10,   10,
       32,   61,   12,  638,   31,   31,   31,   64,   13,   10,
       14,   15,   16,   15,   15,   32,   18,   19,   67,   67,
       67,   20,   68,   21,   22,   23,   83,   84,   85,   69,
       70,   87,   93,   90,   88,   91,   86,   97,   94,   95,
      635,  123,  123,  123,   92,   98,   96,  115,   61,  152,
       24,   25,   14,   15,   16,   15,   15,  116,   18,   19,
      100,  470,  108,   20,  109,   21,   22,   23,  101,  142,
      143,  102,  123,  123,  123,  110,  103,  104,  111,  153,

      528,  112,   67,   67,   67,  127,  130,   34,  154,  634,
      131,  155,   24,   25,   15,   16,   15,   15,  159,   26,
       22,  157,  160,  158,   27,  162,   21,   22,   28,  163,
      164,  181,  177,   61,  123,  123,  123,  219,  191,  209,
      165,  178,  192,  202,  224,  179,  226,  210,  635,  225,
      231,  220,  278,   29,   22,   15,   16,   15,   15,  203,
       26,   22,  262,  232,  227,   27,  269,   21,   22,   28,
      263,  264,  265,  271,  270,  275,  266,  292,  280,  279,
      282,  272,  288,  276,  293,  267,  281,  634,  283,  633,
      289,  310,  310,  310,   29,   22,   33,   33,   33,   33,

       34,   33,   33,  302,  314,  321,   33,  325,  315,  322,
      330,  303,  319,  319,  319,  326,  328,  262,  331,  370,
      329,  310,  310,  310,  319,  319,  319,  371,  632,  381,
      386,   36,   33,   37,  387,  631,  335,  631,   38,   39,
       40,   41,   42,   43,   44,  382,   45,   46,  388,   47,
      630,   48,  336,   49,   50,   51,  389,   52,   53,   54,
       55,   56,  504,  391,  337,  396,  505,   59,   59,  399,
       60,  392,   59,  397,  338,  400,   59,  339,  402,  414,
      340,  408,  408,  408,  403,  421,  426,  415,  434,  436,
      440,  482,  487,  422,  427,  629,  435,  437,  441,  483,

      488,   59,   59,   59,   59,   59,   59,   61,   59,   59,
      446,  446,  446,   59,  452,  452,  452,  457,  457,  457,
      459,  408,  408,  408,  490,  628,  494,  507,  620,  460,
      619,  508,  491,  461,  495,  446,  446,  446,   63,   59,
       33,   33,   33,   71,   34,   33,   33,  511,  618,  627,
       33,  512,  452,  452,  452,  514,  514,  514,  457,  457,
      457,  521,  531,  540,  542,  522,  514,  514,  514,  554,
      532,  541,  543,  555,  626,   33,   33,   72,   72,   72,
       72,   72,  561,  561,  561,  581,   74,  586,  586,  586,
      625,   72,  614,  582,  587,  587,  587,  589,  591,  591,

      591,  590,  592,  593,  561,  561,  561,  594,  595,  595,
      595,  586,  586,  586,  587,  587,  587,  623,   75,   76,
       77,  614,   78,  621,  608,   79,  610,  610,  610,  615,
       80,  620,   81,  591,  591,  591,  619,  605,   82,   56,
      595,  595,  595,  636,  604,   59,   59,  637,   60,  603,
       59,  610,  610,  610,   59,  622,  622,  622,  624,  624,
      624,  622,  622,  622,  624,  624,  624,  639,  639,  639,
      639,  639,  639,  602,  618,  600,  617,  598,  616,   59,
       59,   59,   59,   59,  118,   61,   59,   59,  613,  612,
      611,   59,  585,  584,  583,  609,  581,  608,  607,  606,

      605,  576,  604,  603,  573,  602,  571,  601,  600,  599,
      598,  597,  565,  596,  562,  560,   59,   59,  119,  119,
      119,  119,  119,  559,  588,  551,  585,  121,  549,  584,
      583,  545,  119,  580,  579,  542,  578,  540,  577,  576,
      575,  574,  573,  572,  571,  570,  531,  569,  568,  567,
      566,  565,  524,  564,  563,  562,  518,  560,  516,  122,
       72,   72,   72,   72,   72,  559,  558,  557,  556,   74,
      553,  552,  551,  550,   72,  549,  500,  548,  547,  546,
      545,  544,  494,  539,  490,  538,  537,  487,  486,  536,
      535,  534,  482,  481,  480,  479,  478,  533,  476,  475,

      474,   75,   72,   72,   72,   72,   72,  530,  529,  527,
      526,   74,  525,  524,  523,  520,   72,  519,  459,  518,
      517,  516,  515,  513,  510,  509,  506,  503,  442,  502,
      440,  501,  500,  499,  436,  498,  434,  497,  496,  493,
      492,  489,  426,   75,  119,  119,  119,  119,  119,  486,
      485,  484,  421,  121,  481,  480,  479,  478,  119,  477,
      414,  476,  475,  474,  473,  409,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  396,  458,  456,
      391,  455,  454,  388,  453,  122,  119,  119,  119,  119,
      119,  451,  450,  449,  448,  121,  447,  445,  444,  376,

      119,  443,  374,  442,  439,  370,  438,  433,  432,  431,
      430,  429,  428,  425,  424,  423,  420,  419,  418,  417,
      351,  350,  416,  413,  412,  411,  410,  122,   33,   33,
       33,   33,   34,   33,   33,  409,  407,  406,   33,  405,
      404,  401,  398,  395,  394,  330,  393,  390,  325,  385,
      384,  383,  380,  379,  378,  312,  377,  376,  375,  374,
      373,  372,  369,   33,   33,   59,   59,   59,   59,   61,
       59,   59,  302,  368,  367,   59,  299,  366,  365,  296,
      364,  363,  362,  361,  360,  359,  358,  288,  357,  356,
      355,  354,  353,  282,  352,  280,  351,  278,  350,  349,

       59,   59,   33,   33,   33,   33,   34,   33,   33,  275,
      348,  347,   33,  346,  271,  345,  269,  344,  343,  342,
      341,  334,  333,  332,  327,  324,  323,  320,  318,  317,
      316,  313,  312,  311,  309,  308,  307,   33,   33,   59,
       59,   59,   59,   61,   59,   59,  306,  305,  304,   59,
      234,  301,  300,  299,  298,  297,  296,  295,  294,  291,
      290,  287,  286,  285,  284,  277,  211,  274,  273,  268,
      261,  260,  259,  258,   59,   59,   11,   11,   11,   11,
       11,   17,   17,   17,   17,   17,   14,   14,   14,   14,
       14,   30,   30,   30,   30,   30,   33,   33,   35,   35,

       56,  257,   56,   58,  256,   58,   58,   59,   59,   62,
       62,   73,   73,   73,   73,  120,  120,  120,  120,   72,
       72,   72,   72,  119,  119,  119,  119,  186,  186,  242,
      242,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  180,  241,  177,  240,  239,  238,
      237,  236,  235,  234,  233,  230,  229,  228,  223,  222,
      221,  218,  217,  216,  215,  214,  213,  152,  212,  211,
      208,  207,  206,  205,  204,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  190,  189,  188,  187,  185,  184,
      183,   61,  182,  180,  176,  175,  174,  173,  172,  171,

      170,  169,  168,  167,  166,  161,  156,  151,  150,  149,
      148,  147,  146,  145,  144,  141,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  129,   34,  128,  126,  125,
      124,   65,   61,   61,   57,  117,  114,  113,  107,  106,
      105,   99,   89,   34,   34,   66,   61,   61,   61,   65,
       61,   57,   34,  640,    9,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640

    } ;

static const flex_int16_t yy_chk[1098] =
    {   0,
        1,    1,    1,    1,    1,    0,    0,    1,    0,    7,
        7,    7,    0,    1,    1,    2,    2,    2,    2,    2,
        7,   20,    2,  636,    8,    8,    8,   20,    2,    2,
        3,    3,    3,    3,    3,    8,    3,    3,   31,   31,
       31,    3,   32,    3,    3,    3,   38,   38,   39,   32,
       32,   40,   43,   42,   40,   42,   39,   45,   43,   44,
      635,   64,   64,   64,   42,   45,   44,   54,   64,   97,
        3,    3,    4,    4,    4,    4,    4,   54,    4,    4,
       47,  470,   51,    4,   51,    4,    4,    4,   47,   88,
       88,   47,   66,   66,   66,   51,   47,   47,   51,   97,

      470,   51,   67,   67,   67,   71,   77,   71,   98,  634,
       77,   98,    4,    4,    5,    5,    5,    5,  101,    5,
        5,  100,  101,  100,    5,  103,    5,    5,    5,  103,
      104,  118,  116,  118,  123,  123,  123,  159,  133,  149,
      104,  116,  133,  143,  163,  116,  164,  149,  632,  163,
      168,  159,  214,    5,    5,    6,    6,    6,    6,  143,
        6,    6,  204,  168,  164,    6,  207,    6,    6,    6,
      204,  205,  205,  208,  207,  212,  205,  224,  215,  214,
      216,  208,  221,  212,  224,  205,  215,  630,  216,  629,
      221,  241,  241,  241,    6,    6,   12,   12,   12,   12,

       12,   12,   12,  233,  246,  252,   12,  255,  246,  252,
      258,  233,  250,  250,  250,  255,  257,  262,  258,  304,
      257,  310,  310,  310,  319,  319,  319,  304,  628,  317,
      323,   12,   12,   13,  323,  627,  262,  626,   13,   13,
       13,   13,   13,   13,   13,  317,   13,   13,  324,   13,
      625,   13,  262,   13,   13,   13,  324,   13,   13,   13,
       13,   17,  444,  327,  263,  333,  444,   17,   17,  335,
       17,  327,   17,  333,  263,  335,   17,  263,  337,  348,
      263,  342,  342,  342,  337,  356,  360,  348,  367,  368,
      372,  420,  425,  356,  360,  623,  367,  368,  372,  420,

      425,   17,   17,   19,   19,   19,   19,   19,   19,   19,
      379,  379,  379,   19,  385,  385,  385,  393,  393,  393,
      395,  408,  408,  408,  428,  621,  431,  447,  620,  395,
      619,  447,  428,  395,  431,  446,  446,  446,   19,   19,
       35,   35,   35,   35,   35,   35,   35,  450,  618,  617,
       35,  450,  452,  452,  452,  453,  453,  453,  457,  457,
      457,  463,  473,  492,  493,  463,  514,  514,  514,  509,
      473,  492,  493,  509,  616,   35,   35,   36,   36,   36,
       36,   36,  519,  519,  519,  546,   36,  552,  552,  552,
      615,   36,  614,  546,  553,  553,  553,  556,  557,  557,

      557,  556,  558,  558,  561,  561,  561,  558,  563,  563,
      563,  586,  586,  586,  587,  587,  587,  612,   36,   37,
       37,  596,   37,  609,  608,   37,  588,  588,  588,  596,
       37,  607,   37,  591,  591,  591,  606,  605,   37,   58,
      595,  595,  595,  633,  604,   58,   58,  633,   58,  603,
       58,  610,  610,  610,   58,  611,  611,  611,  613,  613,
      613,  622,  622,  622,  624,  624,  624,  638,  638,  638,
      639,  639,  639,  602,  601,  600,  599,  598,  597,   58,
       58,   62,   62,   62,   62,   62,   62,   62,  593,  592,
      589,   62,  585,  584,  583,  582,  581,  580,  579,  578,

      577,  576,  575,  574,  573,  572,  571,  570,  569,  568,
      567,  566,  565,  564,  562,  560,   62,   62,   63,   63,
       63,   63,   63,  559,  554,  551,  550,   63,  549,  548,
      547,  545,   63,  544,  543,  542,  541,  540,  539,  538,
      537,  536,  535,  534,  533,  532,  531,  530,  528,  527,
      526,  525,  524,  523,  521,  520,  518,  517,  516,   63,
       73,   73,   73,   73,   73,  515,  513,  511,  510,   73,
      507,  504,  503,  502,   73,  501,  500,  499,  498,  497,
      496,  495,  494,  491,  490,  489,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  479,  478,  477,  476,  475,

      474,   73,   74,   74,   74,   74,   74,  472,  471,  469,
      467,   74,  466,  465,  464,  462,   74,  460,  459,  458,
      456,  455,  454,  451,  449,  448,  445,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  430,
      429,  427,  426,   74,  120,  120,  120,  120,  120,  424,
      423,  422,  421,  120,  419,  418,  417,  416,  120,  415,
      414,  413,  412,  411,  410,  409,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  394,  392,
      391,  390,  389,  388,  386,  120,  121,  121,  121,  121,
      121,  384,  383,  382,  381,  121,  380,  378,  377,  376,

      121,  375,  374,  373,  371,  370,  369,  366,  365,  364,
      363,  362,  361,  359,  358,  357,  355,  354,  353,  352,
      351,  350,  349,  347,  346,  345,  344,  121,  127,  127,
      127,  127,  127,  127,  127,  343,  341,  340,  127,  339,
      338,  336,  334,  332,  331,  330,  328,  326,  325,  321,
      320,  318,  316,  314,  313,  312,  311,  309,  308,  307,
      306,  305,  303,  127,  127,  181,  181,  181,  181,  181,
      181,  181,  302,  301,  300,  181,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,

      181,  181,  186,  186,  186,  186,  186,  186,  186,  275,
      274,  273,  186,  272,  271,  270,  269,  268,  267,  265,
      264,  261,  260,  259,  256,  254,  253,  251,  249,  248,
      247,  245,  244,  243,  240,  239,  238,  186,  186,  242,
      242,  242,  242,  242,  242,  242,  237,  236,  235,  242,
      234,  232,  231,  230,  229,  228,  227,  226,  225,  223,
      222,  220,  219,  218,  217,  213,  211,  210,  209,  206,
      203,  202,  201,  200,  242,  242,  641,  641,  641,  641,
      641,  642,  642,  642,  642,  642,  643,  643,  643,  643,
      643,  644,  644,  644,  644,  644,  645,  645,  646,  646,

      647,  199,  647,  648,  198,  648,  648,  649,  649,  650,
      650,  651,  651,  651,  651,  652,  652,  652,  652,  653,
      653,  653,  653,  654,  654,  654,  654,  655,  655,  656,
      656,  197,  196,  195,  194,  193,  191,  190,  189,  188,
      187,  185,  184,  183,  180,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  167,  166,  165,  162,  161,
      160,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      148,  147,  146,  145,  144,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  132,  131,  130,  129,  126,  125,
      124,  122,  119,  117,  115,  114,  113,  112,  111,  110,

      109,  108,  107,  106,  105,  102,   99,   96,   95,   94,
       93,   92,   91,   90,   89,   87,   86,   85,   84,   83,
       82,   81,   80,   79,   78,   76,   75,   72,   70,   69,
       68,   65,   61,   59,   57,   55,   53,   52,   50,   49,
       48,   46,   41,   34,   33,   27,   25,   24,   23,   21,
       18,   16,   11,    9,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  640,  640,  640,  640,  640,  640

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[118] =
    {   0,
       34,   39,   44,   49,   55,   61,   67,   72,   77,   82,
       86,   91,   96,  101,  106,  111,  116,  121,  125,  130,
      134,  139,  144,  149,  154,  158,  163,  168,  173,  178,
      183,  188,  193,  198,  203,  208,  213,  218,  223,  228,
      233,  238,  243,  248,  253,  258,  263,  268,  273,  278,
      283,  288,  293,  298,  302,  307,  312,  317,  322,  327,
      331,  336,  340,  345,  349,  354,  359,  364,  369,  374,
      379,  384,  389,  394,  399,  404,  409,  414,  419,  424,
      429,  434,  439,  444,  449,  454,  459,  464,  469,  474,
      479,  484,  489,  494,  499,  504,  508,  518,  523,  528,

      534,  539,  544,  549,  554,  559,  564,  569,  574,  579,
      585,  590,  596,  606,  616,  623,  634
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "t3-lex.l"



#line 11 "t3-lex.l"
  /* stuff from t3-lex.l */
#include <math.h>
#include "y.tab.h"
#define BUFMAX 16000

int enter_case = 0;

char buf[BUFMAX] = {0};
char * buf_ptr = buf;

static int parse_stringdata();
static int parse_quoted_arg();
static int parse_curly_brased_arg();

#line 1018 "t3-lex.c"
#line 1019 "t3-lex.c"

#define INITIAL 0
#define ARGSTART 1
#define SWITCHARGSTART 2
#define CASESTART 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 32 "t3-lex.l"


#line 1305 "t3-lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 641 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1055 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 118 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 118 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 119 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 34 "t3-lex.l"
{
  yylval.str = "";
  return(ELSE);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 39 "t3-lex.l"
{
  yylval.str = "";
  /* do nothing */
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 44 "t3-lex.l"
{
  yylval.str = "";
  /* do nothing */
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "t3-lex.l"
{
  yylval.str = "";
  BEGIN(ARGSTART);
  return(COMMENT);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "t3-lex.l"
{
  yylval.str = "";
  BEGIN(ARGSTART);
  return(WS);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "t3-lex.l"
{
  yylval.str = "";
  BEGIN(ARGSTART);
  return(ELSEIF);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(IFBEGIN);
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 72 "t3-lex.l"
{
  
  return(BREAK);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 77 "t3-lex.l"
{
  
  return(CONTINUE);
}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 82 "t3-lex.l"
{
  return(IFEND);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(INCR);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(INCRN);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 96 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(EXPR);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(EXPRTO);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(FOREACHBEGIN);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(FORMAT);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 116 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(FORMATTO);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(REGEXP);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 125 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(REGEXPTO);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 130 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(IFREG);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 134 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(ELSEIFREG);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 139 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(REGSUB);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 144 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(REGSUBTO);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 149 "t3-lex.l"
{
   BEGIN(ARGSTART);
   return(XRESOURCE);
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 154 "t3-lex.l"
{
  return(FOREACHENDCMD);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 158 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LAPPEND);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 163 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LSORTTO);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 168 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LASSIGN);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 173 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LASSIGNTO);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 178 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LINDEX);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 183 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LINDEXTO);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 188 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LINSERTTO);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 193 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LIST);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 198 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LISTTO);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 203 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LLENGTH);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 208 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LLENGTHTO);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 213 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LRANGE);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 218 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LRANGETO);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 223 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LREPEAT);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 228 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LREPEATTO);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 233 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LREPLACE);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 238 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LREPLACETO);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 243 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LREVERSETO);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 248 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LREVERSE);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 253 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LSEARCHTO);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 258 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LSEARCH);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 263 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(LSET);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 268 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICTTO);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 273 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICT);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 278 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICTFILTER);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 283 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICTFILTERTO);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 288 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICTPRINT);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 293 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICTFORBEGIN);
}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 298 "t3-lex.l"
{
  return(DICTFOREND);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 302 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(DICTWITHBEGIN);
}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 307 "t3-lex.l"
{
  return(DICTWITHEND);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 312 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(SCAN);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 317 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(SCANTO);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 322 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(NSEVALBEGIN);
}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 327 "t3-lex.l"
{
  return(NSEVALEND);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 331 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(NSBEGIN);
}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 336 "t3-lex.l"
{
  return(NSEND);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 340 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(PROCBEGIN);
}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 345 "t3-lex.l"
{
  return(PROCEND);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 349 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(VARIABLE);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 354 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(SET);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 359 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(GET);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 364 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(STRING);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 369 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(STRINGTO);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 374 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(SPLIT);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 379 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(SPLITTO);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 384 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(ENCODING);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 389 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(ENCODINGTO);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 394 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(CLOCK);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 399 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(CLOCKTO);
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 404 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(INFO);
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 409 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(INFOTO);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 414 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(ARRAY);
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 419 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(ARRAYTO);
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 424 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(CONCAT);
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 429 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(CONCATTO);
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 434 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(JOIN);
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 439 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(JOINTO);
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 444 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(APPEND);
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 449 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(APPENDTO);
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 454 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(BINARY);
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 459 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(BINARYTO);
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 464 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(GLOB);
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 469 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(GLOBTO);
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 474 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(FILEX);
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 479 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(FILEXTO);
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 484 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(UNSET);
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 489 "t3-lex.l"
{
  BEGIN(SWITCHARGSTART);
  return(SWITCHBEGIN);
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 494 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(CASEBEGIN);
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 499 "t3-lex.l"
{
  BEGIN(INITIAL);
  return(DEFAULTCASEBEGIN);
}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 504 "t3-lex.l"
{
  /* do nothing whitespace allowed between case/switch tags */
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 508 "t3-lex.l"
{
  /* error */
  yy_state_type previous_state = yy_get_previous_state();
  printf ( " => BAD TEXT IN SWITCH/CASE: Error! '%s' PREVIOUS STATE = '%i'\n",
        yytext,
       (int)previous_state );
  yylval.str = "ERROR: BAD TEXT IN SWITCH/CASE";
  return(BADTEXTINSWITCH);
}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 518 "t3-lex.l"
{
  BEGIN(INITIAL);
  return(SWITCHEND);
}
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 523 "t3-lex.l"
{
  BEGIN(CASESTART);
  return(CASEEND);
}
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 528 "t3-lex.l"
{
  BEGIN(CASESTART);
  return(CASEEND);
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 534 "t3-lex.l"
{
  BEGIN(ARGSTART);
  return(WHILEBEGIN);
}
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 539 "t3-lex.l"
{
  BEGIN(INITIAL);
  return(WHILEEND);
}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 544 "t3-lex.l"
{
    yylval.str = yytext;
    return(VAR);
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 549 "t3-lex.l"
{
    yylval.str = yytext;
    return(VAR);
}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 554 "t3-lex.l"
{
    yylval.str = yytext;
    return(VAR);
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 559 "t3-lex.l"
{
    yylval.str = yytext;
    return(ARG);
}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 564 "t3-lex.l"
{
    yylval.str = yytext;
    return(ARG);
}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 569 "t3-lex.l"
{
    yylval.str = yytext;
    return(ARG);
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 574 "t3-lex.l"
{ 
  yylval.str = "";
  /* do nothing else */ 
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 579 "t3-lex.l"
{ 
  yylval.str = "ERROR: OPEN BRACKET IN ARGS";
  /* do nothing else, let bison exit */ 
  return(BADWSINARG);
}
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 585 "t3-lex.l"
{
  yylval.str = "ERROR: BAD WHITESPACE";
  return(BADWSINARG);
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 590 "t3-lex.l"
{
  yylval.str = yytext;
  /* printf ( "   ARG: Naked arg '%s'\n", yytext); */
  return(ARG);
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 596 "t3-lex.l"
{
  unput('"');
  int len = parse_quoted_arg();
  if (len >= 2) {
      yylval.str = buf;
      /* printf("len = %i, yytext = '%s' ", len, buf); */
  }
  return(ARG);
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 606 "t3-lex.l"
{
  unput('\{');
  int len = parse_curly_brased_arg();
  if (len >= 2) {
      yylval.str = buf;
      /* printf("len = %i, yytext = '%s' ", len, buf); */
  }
  return(ARG);
}
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
#line 616 "t3-lex.l"
{
  /* printf( "      CLOSETAG: Eat Whitespace... ']' yytext = '%s'\n", yytext ); */
  yylval.str = '\0';
  BEGIN(INITIAL);
  return(CLOSETAG);
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 623 "t3-lex.l"
{ 
  /* printf( "      CLOSETAG: Finished args... '/]' yytext = '%s'\n", yytext ); */
  yylval.str = '\0';
  if (YYSTATE == ARGSTART) {
      BEGIN(INITIAL);
  } else {
      BEGIN(CASESTART);
  }
  return(CLOSETAG);
}
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 634 "t3-lex.l"
{
  unput(yytext[0]);
  /* printf( "Starting to parse_stringdata()"); */
  int len = parse_stringdata();
  yylval.str = buf;
  return(STRINGDATA);
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 642 "t3-lex.l"
ECHO;
	YY_BREAK
#line 2373 "t3-lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ARGSTART):
case YY_STATE_EOF(SWITCHARGSTART):
case YY_STATE_EOF(CASESTART):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 641 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 641 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 640);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 642 "t3-lex.l"


/*
 functions used in this file
*/
static int parse_stringdata() {

  int i = 0;
  int level = 1;
  char c;
  char ctmp;

  while ( (i < BUFMAX) && ( (c = input()) != EOF )   )
  {
    
    switch (c) 
    {
    case '\{' :
    case '"':
      /* things which need escaping */
      /* printf("...Escaping '%c'\n", c); */
      buf[i] = '\\';
      i++;
      buf[i] = c;
      i++;
      break;
    case '\\':
      
      /* must step over backslash plus following char */
      
      ctmp = input();
      buf[i] = '\\';
      i++;
      buf[i] = ctmp;
      i++;
      break;
    case '\[':
    case '$':
      if (i == 0) {
       /* pattern doesn't match existing 
        * variable or command
        */
       buf[i] = '\\';
       i++;
       buf[i] = c;
       i++;
       break;
      }
      /* end of the line, all strings end with closing double quote */
      unput(c);
      /* printf("End of string with '%c'\n", c); */
      buf[i] = '\0';
      return (i);
    default:
      /*printf("buffing '%c' at buf[%i]\n", c, i); */
      buf[i] = c;
      i++;
      break;
    }   /* end switch */
    
  }    /* end while */

  /* all strings end with closing double quote */
  /*printf("ran out of data, cleaning up\n"); */
  buf[i] = '\0';
  return (i);
}


static int parse_curly_brased_arg() {

  int i = 0;
  int level = 1;
  char c;
  char ctmp;
  
  
  if ( (c = input()) != '\{' )
    return i;
  else
    buf[i] = '\{';
  
  while ( (c = input()) != EOF  && (i < BUFMAX) )
  {
      
    i++;
      
    switch (c) 
    {
    case '\{' :
      
      level++;
      buf[i] = c;
      break;
      
    case '}' :
      
      level--;
      buf[i] = '}';
      
      if (level == 0) 
	{
	  
	  c = input();
	  
	  if (c == ']' || c == ' ' || c == '\t') {
	    i++;
	    buf[i] = '\0';
	    unput(c);
	    /* printf("buf = '%s'", buf); */
	    return i;
	  } else if (c == '/') {
	    
	    ctmp = input();
	    
	    if (ctmp == ']') {
	      i++;
	      buf[i] = '\0';
	      unput(ctmp);
	      unput(c);
	      return i;
	      /* printf("buf = '%s'", buf); */
	    } else {
	      unput(ctmp);
	      unput(c);
	      return 0;
	    }
	    
	  } else {
	    /* illegal char following braced string */
	    /* printf("illegal char following braced string, '%c'\n", c); */
	    unput(c);
	    return 0;
	  }
	}
      break;
      
    case '\\':
      
      /* must step over backslash plus following char */
      
      ctmp = input();
      buf[i] = '\\';
      i++;
      buf[i] = ctmp;
      break;
      
    case '\[':
      
      /* must escape bracket char */
      
      buf[i] = '\\';
      i++;
      buf[i] = c;
      
      break;
    default:
      
      buf[i] = c;
      break;
      
    }   /* end switch */
    
  }    /* end while */
}


static int parse_quoted_arg() {

   int i = 0;
   char c;
   char ctmp;

   if ( (c = input()) != '\"' ) {
      return i;
   } else {
      buf[i] = '\"';
   }

   while ( (c = input()) != EOF && (i < BUFMAX) ) {

      i++;

      switch (c) {
      case '\"' :
         /* printf("in case '\"' at i = '%i'\n", i);
            printf("buf = '%s'\n", buf); */
         buf[i] = '\"';

         c = input();

         if (c == ']' || c == ' ' || c == '\t') {
             i++;
             buf[i] = '\0';
             unput(c);
             /* printf("buf = '%s'", buf); */
             return i;
         } else if (c == '/') {

             ctmp = input();

             if (ctmp == ']') {
                i++;
                buf[i] = '\0';
                unput(ctmp);
                unput(c);
                return i;
                /* printf("buf = '%s'", buf); */
             } else {
                unput(ctmp);
                unput(c);
                return 0;
             }

         } else {
             /* illegal char following quoted string */
             /* printf("illegal char following quoted string, '%c'\n", c); */
             unput(c);
             return 0;
         }
         break;

      case '\\':

         /* must step over backslash plus following char */

         ctmp = input();

         buf[i] = '\\';
         i++;
         buf[i] = ctmp;

         break;

      case '[':

         /* must escape bracket char */
         buf[i] = '\\';
         i++;
         buf[i] = c;

         break;
      default:

         /* printf("appending %c to buf\n", c); */
         buf[i] = c;
         break;
      }

      /* printf("i = %i, buf[%i] = %c\n", i, i, buf[i]); */
   }
   return 0;
}









